export const FETCH_ALL_PLAYER = "FETCH_ALL_PLAYER";

export const FETCH_ALL_TEAM = "FETCH_ALL_TEAM";
export const CREATE_TEAM = "CREATE_TEAM";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const ACCEPT_REGISTER = "ACCEPT_REGISTER";
export const FETCH_ONE_TEAM = "FETCH_ONE_TEAM";

export const UPDATE_MATCH = "UPDATE_MATCH";
export const UPDATE_MATCH_RESULT = "UPDATE_MATCH_RESULT";

export const CREATE_TOUR = "CREATE_TOUR";
export const FETCH_ALL_TOUR = "FETCH_ALL_TOUR";
export const UPDATE_CALENDAR = "UPDATE_CALENDAR";
export const CHANGE_TOUR_RULE = "CHANGE_TOUR_RULE";
export const DELETE_REGISTER = "DELETE_REGISTER";
export const END_TOUR = "END_TOUR";

export const CHECK_SIGN_IN = "CHECK_SIGN_IN";
export const GET_USER_LIST = "GET_USER_LIST";
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";

export const FETCH_RANKING_TEAM = "FETCH_RANKING_TEAM";
export const FETCH_RANKING_PLAYER = "FETCH_RANKING_PLAYER";

export const SET_ER_MESSAGE = "SET_ER_MESSAGE";
export const CLR_ER_MESSAGE = "CLR_ER_MESSAGE";
